DROP TABLE IF EXISTS reviews;
-- , users, restaurants;
-- DROP TYPE IF EXISTS noise;

-- CREATE TYPE noise AS ENUM ('Quiet', 'Moderate', 'Energetic');

-- CREATE TABLE restaurants (
--   id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   name VARCHAR(20) NOT NULL
-- );

-- CREATE TABLE users (
--   id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   username TEXT NOT NULL,
--   user_initials varchar(2) NOT NULL,
--   initials_background varchar(20) NOT NULL,
--   location TEXT NOT NULL,
--   vip BOOLEAN NOT NULL
-- );


CREATE TABLE reviews (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review TEXT NOT NULL, 
  overall DECIMAL NOT NULL,
  food DECIMAL NOT NULL,
  service DECIMAL NOT NULL,
  ambience DECIMAL NOT NULL,
  value DECIMAL NOT NULL,
  noise noise NOT NULL,
  would_recommend BOOLEAN NOT NULL,
  date TIMESTAMP WITH TIME ZONE NOT NULL,
  user_id INT NOT NULL REFERENCES users(id),
  restaurant_id INT NOT NULL REFERENCES restaurants(id)
); 
